name: generate things

on:
  # run anytime
  workflow_dispatch:
  
  # push onto the main branch
  push:
    branches:
      - master
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Cache
        uses: actions/cache@v3.0.11
